[package]
name = "rust_rpg_toolkit"
version = "0.1.0"
edition = "2018"

[profile.dev.package."*"]
opt-level = 3

[dependencies]
chrono = "0.4.19"
regex = "1.5.4"
hex = "0.4.3"
#nanoserde = { version = "0.1.29" }
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"

macroquad = { version = "0.3" }
#macroquad-profiler = "0.1"
macroquad-particles = { version = "0.1", features = ["nanoserde"] }
macroquad-tiled = "0.1"

# [patch.crates-io]
# macroquad = { git = "https://github.com/not-fl3/macroquad.git", rev = "1f4c57eaf42" }
# macroquad-particles = { git = "https://github.com/not-fl3/macroquad.git", rev = "1f4c57eaf42" }
# macroquad-tiled = { git = "https://github.com/not-fl3/macroquad.git", rev = "1f4c57eaf42" }
