[package]
name = "rust_rpg_toolkit"
version = "0.1.0"
edition = "2018"

[profile.dev.package."*"]
opt-level = 3

[[example]]
name = "example_project"
path = "examples/example_project/src/main.rs"
crate-type = ["bin"]

[dependencies]
chrono = "0.4.19"
regex = "1.5.4"
hex = "0.4.3"
#nanoserde = { version = "0.1.29" }
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
gilrs = "0.8.1"

macroquad = { version = "0.3.8" }
quad-storage = "0.1.0"
#macroquad-profiler = "0.1"
macroquad-particles = { version = "0.1", features = ["nanoserde"] }
# macroquad-tiled = "0.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
sapp-jsutils = "0.1.5"
