[package]
name = "rust_rpg_toolset_cli"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "mapconv"
path = "mapconv/src/main.rs"

[dependencies]
rust_rpg_toolkit = { path = "../." }

quicli = "0.4.0"
structopt = "0.3.22"
