[package]
name = "rust-rpg-toolkit-cli"
version = "0.0.1"
edition = "2018"

[[bin]]
name = "mapconv"
path = "mapconv/src/main.rs"

[dependencies]
rust-rpg-toolkit = { path = "../.", version = "0.0.1" }

quicli = "0.4.0"
structopt = "0.3.22"
